
import sys
import os

if not os.path.exists("logs/cluster"):
	os.makedirs("logs/cluster")

configfile: "config/config.yaml"
taxa = config["taxa"]

with open("src/genome_list.txt") as handle:
    ids = handle.readlines()

ids = [re.sub("\n", "", id) for id in ids]

include: "rules/bakta.smk"


rule all:
	input:
		rules.keggdecoder.output
