
import sys
import os

if not os.path.exists("logs/cluster"):
	os.makedirs("logs/cluster")

configfile: "config/config.yaml"
taxa = config["taxa"]

ids, = glob_wildcards("../../input_folder/genomes/{sample}.fasta")
# ids = sorted(ids)[:5]

include: "rules/bakta.smk"


rule all:
	input:
		rules.keggdecoder.output
