
import sys
import os

if not os.path.exists("logs/cluster"):
	os.makedirs("logs/cluster")

configfile: "config/config.yaml"
results_path = config["results_path"]

with open("src/genome_list.txt") as handle:
    ids = handle.readlines()

ids = [re.sub("\n", "", id) for id in ids]

include: "rules/gtotree.smk"

rule all:
	input:
		rules.build_phylogenomic_tree.output
