
import sys
import os

if not os.path.exists("logs/cluster"):
	os.makedirs("logs/cluster")

configfile: "config/config.yaml"
results_path = config["results_path"]

ids, = glob_wildcards("../../input_folder/genomes/{id}.fasta")

include: "rules/gtotree.smk"

rule all:
	input:
		rules.build_phylogenomic_tree.output