
configfile: "../../config/config.yaml"

include: "rules/download.smk"
include: "rules/drep.smk"
include: "rules/gtdbtk.smk"
include: "rules/dram_microbial.smk"

rule all:
	input:
		rules.dram_microbial.output.distill
