
import sys
import os

if not os.path.exists("logs/cluster"):
	os.makedirs("logs/cluster")

configfile: "config/config.yaml"
results_path = config["results_path"]

ids, = glob_wildcards("input_folder/genomes/{id}.fasta")

include: "rules/checkm.smk"
include: "rules/drep.smk"
include: "rules/gtdbtk.smk"

rule all:
	input:
		rules.compile_checkm_summary.output,
		rules.gtdbtk_classify.output
