
configfile: "config/config.yaml"

ids, = glob_wildcards("input_folder/genomes/{id}.fasta")

include: "rules/checkm.smk"
include: "rules/drep.smk"
include: "rules/gtdbtk.smk"

rule all:
	input:
		expand(rules.checkm_genome.output, id = ids),
		rules.gtdbtk_classify.output
