
import sys
import os

if not os.path.exists("logs/cluster"):
	os.makedirs("logs/cluster")

configfile: "config/config.yaml"
results_path = config["results_path"]

with open("src/genome_list.txt") as handle:
    ids = handle.readlines()

ids = [re.sub("\n", "", id) for id in ids]

include: "rules/checkm.smk"
include: "rules/drep.smk"
include: "rules/gtdbtk.smk"
include: "rules/dram_microbial.smk"

rule all:
	input:
		rules.compile_checkm_summary.output,
		rules.drep_genomes.output,
		rules.gtdbtk_classify.output,
		rules.dram_distill.output
