###
taxa_name:
  Rokubacteria
email_address:
  muhammad.zarulhanifah@monash.edu
gtdbtk_db:
  /home/mzar0002/ie79_scratch/db/GTDBtk_db/release202/
dram_config:
  /projects/ie79/Sandra/Rokubacteria/config/dram.config
...
