###
taxa_name:
  Rokubacteria
email_address:
  muhammad.zarulhanifah@monash.edu
results_path:
  /fs03/ie79/zarul/Rokubacteria/preliminary/results
gtdbtk_db:
  /home/mzar0002/ie79_scratch/db/GTDBtk_db/release202/
dram_config:
  src/dram.config
...
