
configfile: "config.yaml"

include: "rules/bakta.smk"

ids, = glob_wildcards("../../input_folder/genomes/{sample}.fasta")
ids = sorted(ids)[:5]

rule all:
	input:
		expand(rules.bakta_annotation.output, id = ids)
