__default__:
        etc         : ""
        jobname     : "{rule}.{wildcards}"
        output      : "logs/cluster/{rule}.{wildcards}.out"
        error       : "logs/cluster/{rule}.{wildcards}.err"
build_phylogenomic_tree:
        etc         : "--mem=300G --time=3-00:00:00"
