__default__:
        etc         : ""
        jobname     : "{rule}.{wildcards}"
        output      : "logs/cluster/{rule}.{wildcards}.out"
        error       : "logs/cluster/{rule}.{wildcards}.err"
